language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
services:
  - postgresql
  - mysql
before_install:
    - export TZ=Europe/London
before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -u root -e 'create database test;'
script:
  - mvn clean package -DskipTests=true
  - mvn test -Dtest=UnitTestSuite
  - mvn test -Dtest=MySqlTestSuite
  - mvn test -Dtest=PostgreSqlTestSuite
  - mvn test -Dtest=SqlServerTestSuite
cache:
  directories:
  - $HOME/.m2