language: java
jdk:
  - oraclejdk8
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - postgresql
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot